language: php

sudo: false

branches:
  only:
    - v3.0.x

services:
    -mysql

php:
  - 7.3
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.5
  - WP_VERSION=5.4
  - WP_VERSION=5.3
  - WP_VERSION=5.2
  - WP_VERSION=5.1
  - WP_VERSION=5.0
  - WP_VERSION=4.9

matrix:
  exclude:
    - php: 7.4
      env: WP_VERSION=4.9
    - php: 7.4
      env: WP_VERSION=5.0
    - php: 7.4
      env: WP_VERSION=5.1
    - php: 7.4
      env: WP_VERSION=5.2
    - php: 7.4
      env: WP_VERSION=5.3
    - php: 7.3
      env: WP_VERSION=4.9
    - php: 7.3
      env: WP_VERSION=5.0

before_script:
  - wget https://github.com/woocommerce/woocommerce/archive/4.5.1.tar.gz && tar xf 4.5.1.tar.gz && cp -R woocommerce-4.5.1 ../woocommerce && rm -R woocommerce-4.5.1
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer update
script: vendor/bin/phpunit
